#########################################
# Apple TV
# Last Updated: 2026-09-10T02:38:50.190Z
# Size: 8
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# Apple TV service endpoints for dedicated proxy routing.
#
# $content-hash-v1$:UaVvYsytRUQMNY6A1LqC7-9yfM8wT6RsVSOJSvTIg2M$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN,ocvideo.apple.com
DOMAIN,linear.tv.apple.com
DOMAIN,hls.itunes.apple.com
DOMAIN,hls-amt.itunes.apple.com
DOMAIN,np-edge.itunes.apple.com
DOMAIN,uts-api.itunes.apple.com
DOMAIN,play-edge.itunes.apple.com
################## EOF ##################
