#########################################
# Apple Podcasts
# Last Updated: 2026-09-10T08:47:20.627Z
# Size: 3
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# Apple Podcasts dedicated service endpoints, including transcript API hosts.
#
# $content-hash-v1$:5Ex-yjWzQUrgv8NtmfFXkaNi8zbIko754eXMwTWQLM8$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN-SUFFIX,applepodcasts.com
DOMAIN-SUFFIX,podcasts.apple.com
################## EOF ##################
